//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_warehouse.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AptekaEntities : DbContext
    {
        private static AptekaEntities _context;
        public AptekaEntities()
            : base("name=AptekaEntities")
        {
        }

        public static AptekaEntities GetContext()
        {
            if (_context == null)
            {
                _context = new AptekaEntities();
            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Caterory_drug> Caterory_drug { get; set; }
        public virtual DbSet<Drug> Drug { get; set; }
        public virtual DbSet<Drugstore> Drugstore { get; set; }
        public virtual DbSet<Purchase> Purchase { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<application_fulfillment_report_Result> application_fulfillment_report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<application_fulfillment_report_Result>("application_fulfillment_report");
        }
    
        public virtual ObjectResult<drug_sales_report_Result> drug_sales_report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<drug_sales_report_Result>("drug_sales_report");
        }
    
        public virtual ObjectResult<pharmacy_applications_report_Result> pharmacy_applications_report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pharmacy_applications_report_Result>("pharmacy_applications_report");
        }
    }
}
