//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int id_purchase { get; set; }
        public Nullable<int> id_applications { get; set; }
        public Nullable<int> id_drug { get; set; }
        public Nullable<int> number_of_drugs { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual Drug Drug { get; set; }
    }
}
