//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy_warehouse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id_user { get; set; }
        public string login_user { get; set; }
        public string pass_user { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public int id_role { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
